name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specify the runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout the code from GitHub
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build:prod  # Build for production
      - name: Deploy to EC2 (replace with your deployment script)
        run: |
          scp -o StrictHostKeyChecking=no -i $KEY -r ./* $USER@$HOST:/home/ec2-user/nestjs-app/
          ssh -o StrictHostKeyChecking=no -i $KEY $USER@$HOST << 'EOF'
            cd /home/ec2-user/nestjs-app
            npm install
            pm2 restart nestjs-helloworld || pm2 start npm --name "nestjs-helloworld" -- start
            pm2 save
          EOF

     env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
